# Generated by Django 3.1.2 on 2020-11-27 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='factura',
            name='id_cliente',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='licoreria.cliente'),
        ),
    ]
