# Generated by Django 3.1.2 on 2020-11-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licoreria', '0002_auto_20201127_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_factura',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
    ]
